version: '2'

services:
  work:
# build image with custom tag
    image: "n6_work"
    build:
      context: .
      dockerfile: ./docker/work/Dockerfile
# control the order of service startup
    depends_on:
      - rabbit
      - mysql
      - mongo
      - web
    container_name: n6
    hostname: n6
    volumes:
      - n6_logs:/var/log/n6/
      - work_artifacts:/root/n6/tmp/
    command: ["supervisord", "-c", "etc/supervisord/supervisord.conf"]
    networks:
      - n6net
# This line has been commented out because each new n6 container has new ip address
#       ipv4_address: 172.25.0.101
  web:
    image: "n6_web"
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    hostname: apache
    restart: always
    container_name: web
    ports:
      - "80:80" # redirect permanently to 443
      - "443:443" # n6 Portal
      - "4443:4443" # n6 REST API
      - "4444:4444" # n6 Admin Panel
    networks:
      n6net:
       ipv4_address: 172.25.0.102
  rabbit:
    image: "n6_rabbit"
    build:
      context: .
      dockerfile: ./docker/rabbit/Dockerfile
    hostname: rabbit
    restart: always
    container_name: rabbit
    ports:
      - "15671:15671" # rabbitmq web management
    networks:
      n6net:
       ipv4_address: 172.25.0.103
  mongo:
    image: "n6_mongo"
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    hostname: mongo
    restart: always
    environment:
      - MONGODB_USER=admin
      - MONGODB_PASS=password
      - MONGODB_DATABASE=admin
      - MONGODB_DATABASEN6=n6
      - AUTH=yes
      - JOURNALING=no
    container_name: mongo
    ports:
      - "27017:27017" # used by MongoDB
    networks:
      n6net:
       ipv4_address: 172.25.0.104
  mysql:
    image: "n6_mysql"
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      n6net:
       ipv4_address: 172.25.0.105

volumes:
  work_artifacts: {}
  n6_logs: {}

networks:
  n6net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
