# Copyright (c) 2018-2025 NASK. All rights reserved.

from n6lib.const import (
    CERTIFICATE_SERIAL_NUMBER_HEXDIGIT_NUM,
    CLIENT_ORGANIZATION_MAX_LENGTH,
)
from n6lib.data_spec.fields import (
    IPv4NetField,
    CCField,
    SourceField,
)


MYSQL_ENGINE = 'InnoDB'
MYSQL_CHARSET = 'utf8mb4'
MYSQL_COLLATE = 'utf8mb4_nopad_bin'

ALEMBIC_DB_CONFIGURATOR_CONFIG_SECT_ENVIRON_VAR_NAME = (
    'N6_ALEMBIC_ENV_AUTH_DB_CONFIGURATOR_CONFIG_SECT')
ALEMBIC_DB_CONFIGURATOR_SETTINGS_DICT_ENVIRON_VAR_NAME = (
    'N6_ALEMBIC_ENV_AUTH_DB_CONFIGURATOR_SETTINGS_DICT')

CLIENT_CA_PROFILE_NAME = 'client'
SERVICE_CA_PROFILE_NAME = 'service'

ORG_REQUEST_STATUS_NEW = 'new'
ORG_REQUEST_STATUS_BEING_PROCESSED = 'being_processed'
ORG_REQUEST_STATUS_ACCEPTED = 'accepted'
ORG_REQUEST_STATUS_DISCARDED = 'discarded'
ORG_REQUEST_STATUSES = {
    ORG_REQUEST_STATUS_NEW,
    ORG_REQUEST_STATUS_BEING_PROCESSED,
    ORG_REQUEST_STATUS_ACCEPTED,
    ORG_REQUEST_STATUS_DISCARDED,
}
ORG_REQUEST_PENDING_STATUSES = {
    ORG_REQUEST_STATUS_NEW,
    ORG_REQUEST_STATUS_BEING_PROCESSED,
}

WEB_TOKEN_TYPE_FOR_LOGIN = 'for_login'
WEB_TOKEN_TYPE_FOR_MFA_CONFIG = 'for_mfa_config'
WEB_TOKEN_TYPE_FOR_PASSWORD_RESET = 'for_password_reset'
WEB_TOKEN_TYPES = {
    WEB_TOKEN_TYPE_FOR_LOGIN,
    WEB_TOKEN_TYPE_FOR_MFA_CONFIG,
    WEB_TOKEN_TYPE_FOR_PASSWORD_RESET
}

MAX_LEN_OF_ORG_ID = CLIENT_ORGANIZATION_MAX_LENGTH
MAX_LEN_OF_CERT_SERIAL_HEX = CERTIFICATE_SERIAL_NUMBER_HEXDIGIT_NUM
MAX_LEN_OF_COUNTRY_CODE = CCField.max_length
MAX_LEN_OF_IP_NETWORK = IPv4NetField.max_length
MAX_LEN_OF_SOURCE_ID = SourceField.max_length
assert MAX_LEN_OF_ORG_ID == 32
assert MAX_LEN_OF_CERT_SERIAL_HEX == 20
assert MAX_LEN_OF_COUNTRY_CODE == 2
assert MAX_LEN_OF_IP_NETWORK == 18
assert MAX_LEN_OF_SOURCE_ID == 32

MAX_LEN_OF_ID_HEX = 36
MAX_LEN_OF_PASSWORD_HASH = 60
MAX_LEN_OF_CA_LABEL = MAX_LEN_OF_SYSTEM_GROUP_NAME = MAX_LEN_OF_OFFICIAL_OR_CONTACT_TOKEN = 100
MAX_LEN_OF_DOMAIN_NAME = MAX_LEN_OF_EMAIL = MAX_LEN_OF_GENERIC_ONE_LINE_STRING = 255
MAX_LEN_OF_URL = 2048
MAX_LEN_OF_UUID4 = 36

INVALID_FIELD_TEMPLATE_MSG = 'Value {value!a} caused {exc.__class__.__name__}: {exc}'
