site_name: "n6 Documentation"
site_url: "https://n6.readthedocs.io"
site_description: "The documentation of n6 - a system to collect, manage and distribute security information on a large scale."

copyright: "Copyright (c) 2013-2025 Naukowa i Akademicka Sieć Komputerowa (Research and Academic Computer Network)."
repo_url: "https://github.com/CERT-Polska/n6"
edit_uri: ""

docs_dir: "src"

nav:
  - Home: index.md
  - data_flow_overview.md
  - changelog.md
  - n6’s Public APIs:
      - REST API: usage/restapi.md
      - Stream API: usage/streamapi.md
  - Your Own Instance of n6:
      - Docker-Based Installation: install_and_conf/docker.md
      - Step-by-Step Installation:
          - Step-by-Step Installation: install_and_conf/step_by_step/index.md
          - System Preparation: install_and_conf/step_by_step/system.md
          - Installing n6 Components: install_and_conf/step_by_step/installation.md
          - Configuring n6 Components: install_and_conf/step_by_step/config.md
          - Trying It Out: install_and_conf/step_by_step/check.md
          - Delving Deeper:
#            - XXX: install_and_conf/step_by_step/examining_data_flow.md
            - Managing n6 Pipeline Components with Supervisor: install_and_conf/step_by_step/supervisor.md
            - n6 Portal – Some Finer Points: install_and_conf/step_by_step/portal_finer_points.md
      - Optional Features (selected topics):
          - Optional Features (selected topics): install_and_conf/opt/index.md
          - Running IntelMQ Bots in n6 Pipeline:
              - Running IntelMQ Bots in n6 Pipeline: install_and_conf/opt/intelmq/index.md
              - Installation and Configuration: install_and_conf/opt/intelmq/config.md
              - Running IntelMQ Bots and Message Format Adapters: install_and_conf/opt/intelmq/running.md
          - Knowledge Base in n6 Portal:
              - Knowledge Base in n6 Portal: install_and_conf/opt/knowledge_base/index.md
              - Initialization and Configuration: install_and_conf/opt/knowledge_base/config.md
              - Content Management: install_and_conf/opt/knowledge_base/management.md
              - n6 Portal Backend API: install_and_conf/opt/knowledge_base/backend_api.md
          - Organization Agreements:
              - Organization Agreements: install_and_conf/opt/optional_agreements/index.md
              - The Agreement Model: install_and_conf/opt/optional_agreements/model.md
              - Management in n6 Admin Panel: install_and_conf/opt/optional_agreements/manage.md
              - Appearance in n6 Portal: install_and_conf/opt/optional_agreements/portal.md
              - n6 Portal Backend API: install_and_conf/opt/optional_agreements/api.md
#          - Stream API:
#              - Stream API: install_and_conf/opt/streamapi/index.md
#              - Docker-Based Installation: install_and_conf/opt/streamapi/docker.md
#              - Step-by-Step Installation: install_and_conf/opt/streamapi/step_by_step.md
          - Stream API: install_and_conf/opt/streamapi/docker.md
#  - Developer Guides:
#      - Implementing a New Data Source:
#          - Implementing a New Data Source: dev_guides/new_source/index.md
#          - Collectors:
#              - Collectors: dev_guides/new_source/collectors/index.md
#              - dev_guides/new_source/collectors/command.md
#              - dev_guides/new_source/collectors/baseclasses.md
#              - dev_guides/new_source/collectors/state.md
#              - dev_guides/new_source/collectors/testing.md
#          - Parsers:
#              - Parsers: dev_guides/new_source/parsers/index.md
#              - dev_guides/new_source/parsers/command.md
#              - dev_guides/new_source/parsers/baseclasses.md
#              - dev_guides/new_source/parsers/hifreq.md
#              - dev_guides/new_source/parsers/testing.md

theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: deep purple
  logo: img/n6_logo.png
  features:
    - navigation.indexes
    - navigation.sections

markdown_extensions:
  - admonition
  - meta
  - smarty
  - toc:
      title: "This document's sections"
      permalink: true
      toc_depth: 6
